### ISSUE TITLE
Compile failed with VS2017

### ISSUE THREAD

**Issue by RMTT** [ScrappyCocco/ScrapEngine#39]
I followed your wiki, fisrt  compile the external modules, it's all ok.But when compile the engine itself, there is too many errors:
![image](https://user-images.githubusercontent.com/20596599/80184680-a35b0600-863d-11ea-9c34-8157e784ac1f.png)
It seems cannot find the standark lib of cpp, but i'm not famililar with VS.
There is also some errors like syntax error:
![image](https://user-images.githubusercontent.com/20596599/80184834-e321ed80-863d-11ea-8eb2-0f85edff7502.png)

**Comment by ScrappyCocco** [comment]
1. What version of Windows are you using?
1. What Visual Studio are you using?
1. What WindowsSDK and build tools are you using?
(You can check on Properties on ScrapEngine solution)
(It's better if you compiled all the external modules with this settings)
![image](https://user-images.githubusercontent.com/11294898/80191117-8ca0b900-8615-11ea-9bd7-00b754a8648a.png)

1. **Also**, did you opened the `ScrapEngine.sln` right? Not the `ScrapEngine.vcxproj` alone i hope

**Comment by RMTT** [comment]
1. Windows 10 1909
![image](https://user-images.githubusercontent.com/20596599/80191905-fbe3d080-8648-11ea-89ce-12de62b1a0f7.png)
2. VS Comminity 2017
3. 
![image](https://user-images.githubusercontent.com/20596599/80192029-26358e00-8649-11ea-9593-998af173aabc.png)
4. yeah, right click ScrapEngine.sln and choose open with  VS 2017


Seems just a different with the windows sdk version

**Comment by ScrappyCocco** [comment]
1. Are you sure the compilation of all submodules is succesful? Because as the wiki says

> openal-soft (if the compilation fails, check that the every generated project use Windows SDK <= 10.0.17134.0);

It could still work with that SDK but i just never tried it so it could also generate problems

2. Otherwise try to show me the first error that appear on the compile log when you try to compile the ScrapEngine solution

**Comment by RMTT** [comment]
1. the compile log of build openal-soft
![O_V5RVE@Q@ZAWF}7(}U8$~T](https://user-images.githubusercontent.com/20596599/80192960-955fb200-864a-11ea-8cdb-81c32a79c203.png)
0 failed.
2. The ScrapEngine.log file:
```
  imgui.cpp
  imgui_demo.cpp
  imgui_draw.cpp
  imgui_widgets.cpp
  AudioBuffer.cpp
  WavAudioBuffer.cpp
  AudioContext.cpp
  AudioDevice.cpp
  AudioListener.cpp
  AudioManager.cpp
  AudioSource.cpp
  DebugLog.cpp
  GuiInput.cpp
  InputManager.cpp
  2DAudioComponent.cpp
  3DAudioComponent.cpp
  AudioComponent.cpp
  CameraComponent.cpp
  ComponentsManager.cpp
  MeshComponent.cpp
  Generating Code...
  Compiling...
  BoxRigidBodyComponent.cpp
  CapsuleRigidBodyComponent.cpp
  RigidBodyComponent.cpp
  SphereRigidBodyComponent.cpp
  SComponent.cpp
  BoxTriggerComponent.cpp
  TriggerComponent.cpp
  SGameObject.cpp
  LogicManager.cpp
  LogicManagerView.cpp
  SQuaternion.cpp
  STransform.cpp
  SVector3.cpp
  SceneManager.cpp
  SObject.cpp
  EngineManager.cpp
  CollisionBody.cpp
  BoxShape.cpp
  CapsuleShape.cpp
  CollisionShape.cpp
  Generating Code...
  Compiling...
  SphereShape.cpp
  DiscreteDynamicsWorld.cpp
  PhysicsManager.cpp
  MultiRaycast.cpp
  RaycastResultInfo.cpp
  SingleRaycast.cpp
  RigidBody.cpp
  ConversionUtils.cpp
  Vertex.cpp
  BaseBuffer.cpp
  BufferContainer.cpp
  IndicesBufferContainer.cpp
  VertexBufferContainer.cpp
  BaseCommandBuffer.cpp
  GuiCommandBuffer.cpp
  StandardCommandBuffer.cpp
  BaseFrameBuffer.cpp
  ShadowmappingFrameBuffer.cpp
  ShadowmappingFrameBufferAttachment.cpp
  StandardFrameBuffer.cpp
  Generating Code...
  Compiling...
  GenericBuffer.cpp
  IndexBuffer.cpp
  BaseStagingBuffer.cpp
  ImageStagingBuffer.cpp
  IndicesStagingBuffer.cpp
  VertexStagingBuffer.cpp
  BaseUniformBuffer.cpp
  ShadowmappingUniformBuffer.cpp
  SkyboxUniformBuffer.cpp
  StandardUniformBuffer.cpp
  VertexBuffer.cpp
  Camera.cpp
  CameraFrustum.cpp
  SingletonCommandPool.cpp
  StandardCommandPool.cpp
  VulkanCommandPool.cpp
  VulkanDepthResources.cpp
  BaseDescriptorPool.cpp
  GuiDescriptorPool.cpp
  StandardDescriptorPool.cpp
  Generating Code...
  Compiling...
  BaseDescriptorSet.cpp
  GuiDescriptorSet.cpp
  ShadowmappingDescriptorSet.cpp
  SkyboxDescriptorSet.cpp
  StandardDescriptorSet.cpp
  VulkanDevice.cpp
  VulkanImGui.cpp
  VukanInstance.cpp
  RenderManager.cpp
  RenderManagerView.cpp
  VulkanMemoryAllocator.cpp
  BasicMaterial.cpp
  SimpleMaterial.cpp
  SkyboxMaterial.cpp
  VulkanMeshInstance.cpp
  Mesh.cpp
  VulkanModel.cpp
c:\users\rmt\source\repos\scrapengine\external\assimp\include\assimp\config.h(977): fatal error C1021: invalid preprocessor command 'cmakedefine'
  VulkanModelBuffersPool.cpp
  VulkanModelPool.cpp
  VulkanSimpleMaterialPool.cpp
  Generating Code...
  Compiling...
  VulkanSkyboxInstance.cpp
  BaseVulkanGraphicsPipeline.cpp
  GuiVulkanGraphicsPipeline.cpp
  ShadowmappingPipeline.cpp
  SkyboxVulkanGraphicsPipeline.cpp
  StandardVulkanGraphicsPipeline.cpp
  BaseQueue.cpp
  GraphicsQueue.cpp
  PresentQueue.cpp
  BaseRenderPass.cpp
  GuiRenderPass.cpp
  ShadowmappingRenderPass.cpp
  StandardRenderPass.cpp
  VulkanSemaphoresManager.cpp
  ShaderManager.cpp
  StandardShadowmapping.cpp
  VulkanImageView.cpp
  VulkanSwapChain.cpp
  VulkanColorResources.cpp
  TextureImageView.cpp
  Generating Code...
  Compiling...
  TextureSampler.cpp
  BaseTexture.cpp
  SkyboxStagingTexture.cpp
  SkyboxTexture.cpp
  StandardTexture.cpp
  VulkanValidationLayers.cpp
  GameWindow.cpp
  VulkanSurface.cpp
  UsefulMethods.cpp
  Generating Code...
```

**Comment by ScrappyCocco** [comment]
You have 

> config.h(977): fatal error C1021: invalid preprocessor command 'cmakedefine'

So you forgot to do this:
![image](https://user-images.githubusercontent.com/11294898/80193267-c7f0b700-8618-11ea-90ad-a20c50fa6a27.png)

It's written in here: [https://github.com/ScrappyCocco/ScrapEngine/wiki/How-to-build-the-engine#building-and-running-the-engine](https://github.com/ScrappyCocco/ScrapEngine/wiki/How-to-build-the-engine#building-and-running-the-engine)

**Comment by RMTT** [comment]
Sorry, i'm stupid ,build success after comment this line. 
I thank of that just need comment this when compile assimp failed.
