### ISSUE TITLE
Assimp with vs2017

### ISSUE THREAD

**Issue by MickLilley** [ScrappyCocco/ScrapEngine#43]
f:\projects\github\scrapengine\external\assimp\include\assimp\defs.h(53): fatal error C1083: Cannot open include file: 'assimp/config.h': No such file or directory

Doesn't compile out of the box for debug or release
Can't bulid the sample for obvious reasons - no engine

**Comment by ScrappyCocco** [comment]
Dear MicLilley,
This doesn't compile "out of the box", no, is a very simple project done for personal purposes

But, there are build instructions specified in the readme, so if you go to page: [How to build the engine
](https://github.com/ScrappyCocco/ScrapEngine/wiki/How-to-build-the-engine#building-and-running-the-engine
You'll notice there is:
![image](https://user-images.githubusercontent.com/11294898/107853696-ae269780-6e17-11eb-9f8d-781ac1217daf.png)

**Comment by ScrappyCocco** [comment]
Closed due to inactivity
